### ISSUE TITLE
반응형 헤더 만들기

### ISSUE THREAD

**Issue by hyejeong9526** [project-mulplay/project-mulplay2#42]
## 종류

ISSUE 종류를 선택하세요 (`[ ]` 안에 `x` 표시, `[x]`)

- [x] Refactor (리모델링 재개발)
- [ ] Fix (내가 해결해주지)
- [ ] Bug (삐용삐용 큰일 났어 / 질문)
- [ ] Feature (제가 해냈습니다)

# 📃작업 내용

- 헤더를  (max-width: 768px)이 됐을 때 메뉴 버튼과 로그인 버튼으로 토글이 되게 만듭니다.

**Comment by sojung2** [comment]
로그인 되었을때 헤더가 바뀌는 것도 구현가능하실까요?!

**Comment by hyejeong9526** [comment]
모르겠어요;; // 로그인 상태 헤더는 만들어 놨는데..app.js에  {isLoggedIn ? <LoggedInHeader /> : <LoggedOutHeader />}이 코드가 로그인 되면 헤더도 로그인된 헤더로 바뀌는거 아니에요??
